nacos_server:
  dataId: 'goods_web.json'
  ip: '192.168.1.109'
  port: 8848
nacos_client:
  namespace_id: '09263366-14c0-4d54-acf8-43d3561d740d'
  timeout_ms: 5000
  not_load_cache_at_start: true
  log_dir: "tmp/nacos/log"
  cache_dir: "tmp/nacos/cache"
