nacos_server:
  dataId: 'inventory_srv.json'
  ip: '192.168.1.105'
  port: 8848
nacos_client:
  namespace_id: '3cd0255e-daca-42a7-a754-fb368ae408f9'
  timeout_ms: 5000
  not_load_cache_at_start: true
  log_dir: "tmp/nacos/log"
  cache_dir: "tmp/nacos/cache"
